version: 2
jobs:
  build:
    working_directory: ~/appName
    docker:
      - image: ruby:2.3.1-jessie
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name
    filters:
      branches:
        only: 
          - master
          - staging
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"
  deploy:
    steps:
      - deploy:
          command: echo "deploy to production"
    filters:
      branches:
        only: master
  stage:
    steps:
      - deploy:
          command: echo "deploy to staging"
    filters:
      branches:
        only: staging
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - stage:
        requires: build
      - deploy:
        requires: build
